/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as OrderFailedRouteImport } from './routes/order-failed'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ExhibitionsIndexRouteImport } from './routes/exhibitions/index'
import { Route as ArtworksIndexRouteImport } from './routes/artworks/index'
import { Route as ShopIdRouteImport } from './routes/shop/$id'
import { Route as LoginForgotPasswordRouteImport } from './routes/login/forgot-password'
import { Route as ExhibitionsIdRouteImport } from './routes/exhibitions/$id'
import { Route as ArtworksIdRouteImport } from './routes/artworks/$id'

const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderFailedRoute = OrderFailedRouteImport.update({
  id: '/order-failed',
  path: '/order-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsIndexRoute = ExhibitionsIndexRouteImport.update({
  id: '/exhibitions/',
  path: '/exhibitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksIndexRoute = ArtworksIndexRouteImport.update({
  id: '/artworks/',
  path: '/artworks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginForgotPasswordRoute = LoginForgotPasswordRouteImport.update({
  id: '/login/forgot-password',
  path: '/login/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsIdRoute = ExhibitionsIdRouteImport.update({
  id: '/exhibitions/$id',
  path: '/exhibitions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksIdRoute = ArtworksIdRouteImport.update({
  id: '/artworks/$id',
  path: '/artworks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/artists': typeof ArtistsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-failed': typeof OrderFailedRoute
  '/order-success': typeof OrderSuccessRoute
  '/artworks/$id': typeof ArtworksIdRoute
  '/exhibitions/$id': typeof ExhibitionsIdRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/shop/$id': typeof ShopIdRoute
  '/artworks/': typeof ArtworksIndexRoute
  '/exhibitions/': typeof ExhibitionsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/artists': typeof ArtistsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-failed': typeof OrderFailedRoute
  '/order-success': typeof OrderSuccessRoute
  '/artworks/$id': typeof ArtworksIdRoute
  '/exhibitions/$id': typeof ExhibitionsIdRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/shop/$id': typeof ShopIdRoute
  '/artworks': typeof ArtworksIndexRoute
  '/exhibitions': typeof ExhibitionsIndexRoute
  '/login': typeof LoginIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/artists': typeof ArtistsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-failed': typeof OrderFailedRoute
  '/order-success': typeof OrderSuccessRoute
  '/artworks/$id': typeof ArtworksIdRoute
  '/exhibitions/$id': typeof ExhibitionsIdRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/shop/$id': typeof ShopIdRoute
  '/artworks/': typeof ArtworksIndexRoute
  '/exhibitions/': typeof ExhibitionsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/artists'
    | '/cart'
    | '/checkout'
    | '/order-failed'
    | '/order-success'
    | '/artworks/$id'
    | '/exhibitions/$id'
    | '/login/forgot-password'
    | '/shop/$id'
    | '/artworks/'
    | '/exhibitions/'
    | '/login/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/artists'
    | '/cart'
    | '/checkout'
    | '/order-failed'
    | '/order-success'
    | '/artworks/$id'
    | '/exhibitions/$id'
    | '/login/forgot-password'
    | '/shop/$id'
    | '/artworks'
    | '/exhibitions'
    | '/login'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/artists'
    | '/cart'
    | '/checkout'
    | '/order-failed'
    | '/order-success'
    | '/artworks/$id'
    | '/exhibitions/$id'
    | '/login/forgot-password'
    | '/shop/$id'
    | '/artworks/'
    | '/exhibitions/'
    | '/login/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ArtistsRoute: typeof ArtistsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrderFailedRoute: typeof OrderFailedRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  ArtworksIdRoute: typeof ArtworksIdRoute
  ExhibitionsIdRoute: typeof ExhibitionsIdRoute
  LoginForgotPasswordRoute: typeof LoginForgotPasswordRoute
  ShopIdRoute: typeof ShopIdRoute
  ArtworksIndexRoute: typeof ArtworksIndexRoute
  ExhibitionsIndexRoute: typeof ExhibitionsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-failed': {
      id: '/order-failed'
      path: '/order-failed'
      fullPath: '/order-failed'
      preLoaderRoute: typeof OrderFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions/': {
      id: '/exhibitions/'
      path: '/exhibitions'
      fullPath: '/exhibitions/'
      preLoaderRoute: typeof ExhibitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks/': {
      id: '/artworks/'
      path: '/artworks'
      fullPath: '/artworks/'
      preLoaderRoute: typeof ArtworksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/forgot-password': {
      id: '/login/forgot-password'
      path: '/login/forgot-password'
      fullPath: '/login/forgot-password'
      preLoaderRoute: typeof LoginForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions/$id': {
      id: '/exhibitions/$id'
      path: '/exhibitions/$id'
      fullPath: '/exhibitions/$id'
      preLoaderRoute: typeof ExhibitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks/$id': {
      id: '/artworks/$id'
      path: '/artworks/$id'
      fullPath: '/artworks/$id'
      preLoaderRoute: typeof ArtworksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ArtistsRoute: ArtistsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrderFailedRoute: OrderFailedRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  ArtworksIdRoute: ArtworksIdRoute,
  ExhibitionsIdRoute: ExhibitionsIdRoute,
  LoginForgotPasswordRoute: LoginForgotPasswordRoute,
  ShopIdRoute: ShopIdRoute,
  ArtworksIndexRoute: ArtworksIndexRoute,
  ExhibitionsIndexRoute: ExhibitionsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
