/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExhibitionsIndexRouteImport } from './routes/exhibitions/index'
import { Route as ArtworksIndexRouteImport } from './routes/artworks/index'
import { Route as ExhibitionsIdRouteImport } from './routes/exhibitions/$id'
import { Route as ArtworksIdRouteImport } from './routes/artworks/$id'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsIndexRoute = ExhibitionsIndexRouteImport.update({
  id: '/exhibitions/',
  path: '/exhibitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksIndexRoute = ArtworksIndexRouteImport.update({
  id: '/artworks/',
  path: '/artworks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsIdRoute = ExhibitionsIdRouteImport.update({
  id: '/exhibitions/$id',
  path: '/exhibitions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksIdRoute = ArtworksIdRouteImport.update({
  id: '/artworks/$id',
  path: '/artworks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/artists': typeof ArtistsRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/artworks/$id': typeof ArtworksIdRoute
  '/exhibitions/$id': typeof ExhibitionsIdRoute
  '/artworks/': typeof ArtworksIndexRoute
  '/exhibitions/': typeof ExhibitionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/artists': typeof ArtistsRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/artworks/$id': typeof ArtworksIdRoute
  '/exhibitions/$id': typeof ExhibitionsIdRoute
  '/artworks': typeof ArtworksIndexRoute
  '/exhibitions': typeof ExhibitionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/artists': typeof ArtistsRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/artworks/$id': typeof ArtworksIdRoute
  '/exhibitions/$id': typeof ExhibitionsIdRoute
  '/artworks/': typeof ArtworksIndexRoute
  '/exhibitions/': typeof ExhibitionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/artists'
    | '/login'
    | '/shop'
    | '/artworks/$id'
    | '/exhibitions/$id'
    | '/artworks/'
    | '/exhibitions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/artists'
    | '/login'
    | '/shop'
    | '/artworks/$id'
    | '/exhibitions/$id'
    | '/artworks'
    | '/exhibitions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/artists'
    | '/login'
    | '/shop'
    | '/artworks/$id'
    | '/exhibitions/$id'
    | '/artworks/'
    | '/exhibitions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ArtistsRoute: typeof ArtistsRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  ArtworksIdRoute: typeof ArtworksIdRoute
  ExhibitionsIdRoute: typeof ExhibitionsIdRoute
  ArtworksIndexRoute: typeof ArtworksIndexRoute
  ExhibitionsIndexRoute: typeof ExhibitionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions/': {
      id: '/exhibitions/'
      path: '/exhibitions'
      fullPath: '/exhibitions/'
      preLoaderRoute: typeof ExhibitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks/': {
      id: '/artworks/'
      path: '/artworks'
      fullPath: '/artworks/'
      preLoaderRoute: typeof ArtworksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions/$id': {
      id: '/exhibitions/$id'
      path: '/exhibitions/$id'
      fullPath: '/exhibitions/$id'
      preLoaderRoute: typeof ExhibitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks/$id': {
      id: '/artworks/$id'
      path: '/artworks/$id'
      fullPath: '/artworks/$id'
      preLoaderRoute: typeof ArtworksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ArtistsRoute: ArtistsRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  ArtworksIdRoute: ArtworksIdRoute,
  ExhibitionsIdRoute: ExhibitionsIdRoute,
  ArtworksIndexRoute: ArtworksIndexRoute,
  ExhibitionsIndexRoute: ExhibitionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
